
server:
  port: 8090

spring:
  druid:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house?characterEncoding=UTF-8
    username: root
    password: 123456
    #\u6700\u5927\u8FDE\u63A5\u6570
    maxActive: 30
    #\u6700\u5C0F\u8FDE\u63A5\u6570
    minIdle: 5
    #\u83B7\u53D6\u8FDE\u63A5\u6700\u5927\u7B49\u5F85\u65F6\u95F4
    maxWait: 10000
    #\u89E3\u51B3mysql8\u5C0F\u65F6\u95EE\u9898
    validationQuery: SELECT 'x'
    #\u7A7A\u95F2\u8FDE\u63A5\u68C0\u67E5\u95F4\u9694\u65F6\u95F4
    timeBetweenEvictionRunsMillis: 60000
    #\u7A7A\u95F2\u8FDE\u63A5\u6700\u5C0F\u7A7A\u95F2\u65F6\u95F4\uFF0C\u8FBE\u5230\u8FD9\u4E2A\u65F6\u95F4\u5C5E\u4E8E\u7A7A\u95F2\u8FDE\u63A5
    minEvictableIdleTimeMillis: 300000

  freemarker:
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      auto_import: common/common.ftl as common
 #邮件相关
  mail:
    host: smtp.126.com
    username: hch_alone@126.com
    password: hch123
    properties:
      mail:
        smtp:
          auth: true       #设置是否需要认证，如果为true,那么用户名和密码就必须的
          starttls:
            enable: true #STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
            required: true

#mybatis
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml

file:
  path: /Users/hch/opt/imgs
  prefix: http://127.0.0.1:8087/images
domain:
  name: 127.0.0.1:8090

